name: Continuous Deployment (Build and Release APK)

on: 
  pull_request:
  push:
    branches:
      - main

env: 
  FLUTTER_VERSION: '3.3.8'
  FLUTTER_CHANNEL: 'stable'
  JAVA_VERSION: '12.x'

jobs:
  build:
    name: Continuous Deployment (Build and Release APK)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '3.3.8'
    - name: Install dependencies
      run: flutter pub get
    - name: Build APK
      run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        # the token could be set later in the settings
        # token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
