on: 
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main
      - development
name: Build, and Release apk
jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.3.8'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        # token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
