on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: Build, and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - name: Running pub get
      run: flutter pub get
    - name: Building APK
      run: flutter build apk --debug --split-per-abi
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        # the token could be set later in the settings
        # token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.${{ github.run_number }}
        name: ${{ github.event.release.name }}
        body: ${{ github.event.release.body }}
